### ISSUE TITLE
Beta 2.0.4 crash when including Popp Z-Rain

### ISSUE THREAD

**Issue by AndDym** [mruiter/com.popp#16]
When including the Popp Z-Rain the app crashes, I have sent the log with the following id 3129bc2b-69a2-49b8-b894-536c4b3196e4. Let me know if you want me to test anything.

**Comment by mruiter** [comment]
I didnt get the log file. Could you please run the app in debug mode from athom cli ?
This would give more info since i dont have the device myself

**Comment by AndDym** [comment]
I have run your app from cli and here is the log output. Let me know if you need more information.

─────────────── Logging stdout & stderr ───────────────
(node:11934) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 __appInit listeners added. Use emitter.setMaxListeners() to increase limit
2018-04-03 21:06:38 [log] [PoPPZwave] PoPP Z-wave app is running...
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] ZwaveDevice has been inited
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] ------------------------------------------
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] Node: fb58b156-13b8-4a03-b438-02d2c52caaf0
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - Battery: true
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_ZWAVEPLUS_INFO
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 2
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ZWAVEPLUS_INFO_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ZWAVEPLUS_INFO_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_SENSOR_MULTILEVEL
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 7
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- SENSOR_MULTILEVEL_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- SENSOR_MULTILEVEL_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- SENSOR_MULTILEVEL_SUPPORTED_GET_SENSOR
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- SENSOR_MULTILEVEL_SUPPORTED_SENSOR_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- SENSOR_MULTILEVEL_SUPPORTED_GET_SCALE
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- SENSOR_MULTILEVEL_SUPPORTED_SCALE_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_CONFIGURATION
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- CONFIGURATION_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- CONFIGURATION_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- CONFIGURATION_SET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_ASSOCIATION
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 2
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUPINGS_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUPINGS_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_REMOVE
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_SET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_SPECIFIC_GROUP_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_SPECIFIC_GROUP_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_BATTERY
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- BATTERY_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- BATTERY_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_WAKE_UP
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- WAKE_UP_INTERVAL_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- WAKE_UP_INTERVAL_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- WAKE_UP_INTERVAL_SET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- WAKE_UP_NO_MORE_INFORMATION
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- WAKE_UP_NOTIFICATION
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_METER
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- METER_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- METER_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_DEVICE_RESET_LOCALLY
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- DEVICE_RESET_LOCALLY_NOTIFICATION
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_ASSOCIATION_GRP_INFO
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUP_NAME_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUP_NAME_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUP_INFO_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUP_INFO_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUP_COMMAND_LIST_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUP_COMMAND_LIST_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_POWERLEVEL
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- POWERLEVEL_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- POWERLEVEL_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- POWERLEVEL_SET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- POWERLEVEL_TEST_NODE_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- POWERLEVEL_TEST_NODE_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- POWERLEVEL_TEST_NODE_SET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_VERSION
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- VERSION_COMMAND_CLASS_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- VERSION_COMMAND_CLASS_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- VERSION_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- VERSION_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_MANUFACTURER_SPECIFIC
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- MANUFACTURER_SPECIFIC_GET
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] --- MANUFACTURER_SPECIFIC_REPORT
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_BASIC
2018-04-03 21:06:38 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-03 21:06:39 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-03 21:06:39 [log] [ManagerDrivers] [700168] [0] --- BASIC_GET
2018-04-03 21:06:39 [log] [ManagerDrivers] [700168] [0] --- BASIC_REPORT
2018-04-03 21:06:39 [log] [ManagerDrivers] [700168] [0] --- BASIC_SET
2018-04-03 21:06:39 [log] [ManagerDrivers] [700168] [0] ------------------------------------------
2018-04-03 21:06:39 [log] [ManagerDrivers] [700168] [0]
/node_modules/homey-meshdriver/lib/zwave/system/capabilities/meter_rain/METER.js:6
                return {
                       ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)

--- INFO: com.popp has been killed ---

**Comment by AndDym** [comment]
Hi @mruiter ,
did you find anything that could be causing this crash?

**Comment by pellz0r** [comment]
Same thing happened to me now when I tried to include the Z-rain. Log id d9c84d4c-0f0c-4ac8-89b0-d994c95a40f7.

**Comment by mruiter** [comment]
Confirmed working in latest versions of app
