### ISSUE TITLE
BETA: Crash with Z-Rain

### ISSUE THREAD

**Issue by rschobben** [mruiter/com.popp#19]
App crashes when initializing Z-Rain.

Reproduction: remove Z-Rain, re-pair.

─────────────── Logging stdout & stderr ───────────────
(node:14345) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 __appInit listeners added. Use emitter.setMaxListeners() to increase limit
2018-04-09 20:54:15 [log] [PoPPZwave] PoPP Z-wave app is running...
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] ZwaveDevice has been inited
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] ------------------------------------------
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] Node: 45de69d7-98f6-46fc-8d3a-4c1778711734
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] - Battery: true
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_ZWAVEPLUS_INFO
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Version: 2
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ZWAVEPLUS_INFO_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ZWAVEPLUS_INFO_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_SENSOR_MULTILEVEL
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Version: 7
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- SENSOR_MULTILEVEL_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- SENSOR_MULTILEVEL_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- SENSOR_MULTILEVEL_SUPPORTED_GET_SENSOR
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- SENSOR_MULTILEVEL_SUPPORTED_SENSOR_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- SENSOR_MULTILEVEL_SUPPORTED_GET_SCALE
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- SENSOR_MULTILEVEL_SUPPORTED_SCALE_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_CONFIGURATION
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- CONFIGURATION_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- CONFIGURATION_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- CONFIGURATION_SET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_ASSOCIATION
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Version: 2
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUPINGS_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUPINGS_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_REMOVE
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_SET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_SPECIFIC_GROUP_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_SPECIFIC_GROUP_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_BATTERY
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- BATTERY_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- BATTERY_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_WAKE_UP
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Version: 2
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- WAKE_UP_INTERVAL_CAPABILITIES_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- WAKE_UP_INTERVAL_CAPABILITIES_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- WAKE_UP_INTERVAL_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- WAKE_UP_INTERVAL_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- WAKE_UP_INTERVAL_SET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- WAKE_UP_NO_MORE_INFORMATION
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- WAKE_UP_NOTIFICATION
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_METER
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Version: 4
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- METER_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- METER_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- METER_RESET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- METER_SUPPORTED_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- METER_SUPPORTED_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_DEVICE_RESET_LOCALLY
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- DEVICE_RESET_LOCALLY_NOTIFICATION
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_ASSOCIATION_GRP_INFO
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUP_NAME_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUP_NAME_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUP_INFO_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUP_INFO_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUP_COMMAND_LIST_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- ASSOCIATION_GROUP_COMMAND_LIST_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_POWERLEVEL
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- POWERLEVEL_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- POWERLEVEL_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- POWERLEVEL_SET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- POWERLEVEL_TEST_NODE_GET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- POWERLEVEL_TEST_NODE_REPORT
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] --- POWERLEVEL_TEST_NODE_SET
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_VERSION
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Version: 2
2018-04-09 20:55:50 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] --- VERSION_COMMAND_CLASS_GET
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] --- VERSION_COMMAND_CLASS_REPORT
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] --- VERSION_GET
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] --- VERSION_REPORT
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_MANUFACTURER_SPECIFIC
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] -- Version: 2
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] --- MANUFACTURER_SPECIFIC_GET
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] --- MANUFACTURER_SPECIFIC_REPORT
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] --- DEVICE_SPECIFIC_GET
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] --- DEVICE_SPECIFIC_REPORT
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] - CommandClass: COMMAND_CLASS_BASIC
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] -- Version: 1
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] -- Commands:
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] --- BASIC_GET
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] --- BASIC_REPORT
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] --- BASIC_SET
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] ------------------------------------------
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] 
2018-04-09 20:55:51 [log] [ManagerDrivers] [700168] [0] Node online, getting commandClassId 'BATTERY' for capabilityId 'measure_battery'
/node_modules/homey-meshdriver/lib/zwave/system/capabilities/meter_rain/METER.js:6
		return {
		       ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)

--- INFO: com.popp has been killed ---

**Comment by mruiter** [comment]
Confirmed working in latest versions of app
